const $=id=>document.getElementById(id);const state={connected:false,photos:[],selectedDate:''};
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
async function requestJson(url,options={}){const response=await fetch(url,{cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'요청을 처리하지 못했습니다.');return data}
function initYears(){const current=new Date().getFullYear();$('year-select').innerHTML=Array.from({length:10},(_,i)=>`<option value="${current-i}">${current-i}년</option>`).join('')}
async function refreshSession(){try{const data=await requestJson('/api/photo-kidsnote/session');state.connected=Boolean(data.connected);$('session-state').className=`session-state ${state.connected?'connected':'error'}`;$('session-state').innerHTML=`<span class="status-dot"></span><span>${state.connected?'키즈노트 연결됨':'키즈노트 로그인이 필요합니다'}</span>`;$('btn-kidsnote-session').querySelector('span').textContent=state.connected?'계정 변경':'키즈노트 로그인'}catch(error){toast(error.message)}}
function openLogin(){$('kidsnote-login-error').classList.add('hidden');$('kidsnote-login-modal').classList.remove('hidden');$('kidsnote-login-modal').setAttribute('aria-hidden','false');setTimeout(()=>$('kidsnote-username').focus(),50)}
function closeLogin(){$('kidsnote-login-modal').classList.add('hidden');$('kidsnote-login-modal').setAttribute('aria-hidden','true')}
async function login(event){event.preventDefault();const button=$('btn-kidsnote-login');button.disabled=true;button.querySelector('span').textContent='로그인 중…';try{await requestJson('/api/photo-kidsnote/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('kidsnote-username').value.trim(),password:$('kidsnote-password').value})});$('kidsnote-password').value='';closeLogin();await refreshSession();toast('키즈노트 계정이 연결되었습니다.')}catch(error){$('kidsnote-login-error').textContent=error.message;$('kidsnote-login-error').classList.remove('hidden')}finally{button.disabled=false;button.querySelector('span').textContent='로그인하고 연결하기'}}
async function loadPhotos(){if(!state.connected){openLogin();return}const button=$('btn-load-photos');button.disabled=true;$('lookup-progress').classList.remove('hidden');$('result-area').classList.add('hidden');$('start-guide').classList.add('hidden');try{const data=await requestJson(`/api/pc-photo-sources?year=${encodeURIComponent($('year-select').value)}`);state.photos=data.photos||[];$('date-select').innerHTML='<option value="">전체 날짜</option>'+(data.dates||[]).map(date=>`<option value="${date}">${displayDate(date)} · ${state.photos.filter(photo=>photo.takenAt.startsWith(date)).length}장</option>`).join('');state.selectedDate='';$('result-area').classList.remove('hidden');renderDate();toast(`최신 사진부터 ${state.photos.length}장을 조회했습니다.`)}catch(error){$('start-guide').classList.remove('hidden');toast(error.message)}finally{button.disabled=false;$('lookup-progress').classList.add('hidden')}}
function renderDate(){state.selectedDate=$('date-select').value;const photos=state.selectedDate?state.photos.filter(photo=>photo.takenAt.startsWith(state.selectedDate)):state.photos;$('selected-count').textContent=`${photos.length}장`;$('photo-list').replaceChildren(...photos.map(photoCard));$('photo-list').classList.toggle('hidden',!photos.length);$('empty-result').classList.toggle('hidden',Boolean(photos.length));$('btn-download-date').disabled=!photos.length;$('btn-download-date').querySelector('span').textContent=state.selectedDate?'이 날짜 전체 받기':'연도 전체 받기'}
function photoCard(photo){const card=document.createElement('article');card.className='gallery-card';const image=document.createElement('img');image.loading='lazy';image.src=`/api/pc-photo-sources/${encodeURIComponent(photo.id)}/file`;image.alt='키즈노트 사진 미리보기';const shade=document.createElement('div');shade.className='gallery-shade';const date=document.createElement('span');date.textContent=displayDate(photo.takenAt.slice(0,10));const link=document.createElement('a');link.className='gallery-download';link.href=`/api/pc-photo-sources/${encodeURIComponent(photo.id)}/file?download=1`;link.innerHTML='<span>한 장 받기</span><svg viewBox="0 0 24 24"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"/></svg>';link.addEventListener('click',event=>event.stopPropagation());shade.append(date,link);card.append(image,shade);return card}
function displayDate(value){const date=new Date(`${String(value).slice(0,10)}T00:00:00`);if(Number.isNaN(date.getTime()))return value;return `${date.getFullYear()}년 ${date.getMonth()+1}월 ${date.getDate()}일 (${['일','월','화','수','목','금','토'][date.getDay()]})`}
function downloadDate(){const query=state.selectedDate?`date=${encodeURIComponent(state.selectedDate)}`:`year=${encodeURIComponent($('year-select').value)}`;window.location.assign(`/api/pc-photo-download.zip?${query}`)}
function setColumns(columns){const value=['3','4','5'].includes(String(columns))?String(columns):'3';$('photo-list').classList.remove('columns-3','columns-4','columns-5');$('photo-list').classList.add(`columns-${value}`);document.querySelectorAll('.view-button').forEach(button=>button.classList.toggle('active',button.dataset.columns===value));localStorage.setItem('kidsnote-pc-gallery-columns',value)}
document.addEventListener('DOMContentLoaded',()=>{localStorage.setItem('kidsnote-photo-view','pc');initYears();refreshSession();setColumns(localStorage.getItem('kidsnote-pc-gallery-columns')||'3');if(window.lucide)lucide.createIcons();$('switch-mobile').addEventListener('click',()=>localStorage.setItem('kidsnote-photo-view','mobile'));$('btn-kidsnote-session').addEventListener('click',openLogin);$('kidsnote-login-close').addEventListener('click',closeLogin);$('kidsnote-login-modal').addEventListener('click',event=>{if(event.target===$('kidsnote-login-modal'))closeLogin()});$('kidsnote-login-form').addEventListener('submit',login);$('btn-refresh').addEventListener('click',refreshSession);$('btn-load-photos').addEventListener('click',loadPhotos);$('date-select').addEventListener('change',renderDate);$('btn-download-date').addEventListener('click',downloadDate);document.querySelectorAll('.view-button').forEach(button=>button.addEventListener('click',()=>setColumns(button.dataset.columns)))});
