const $=id=>document.getElementById(id);const state={connected:false,photos:[],date:''};
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
async function requestJson(url,options={}){const response=await fetch(url,{cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'요청을 처리하지 못했습니다.');return data}
function initYears(){const current=new Date().getFullYear();$('year-select').innerHTML=Array.from({length:10},(_,i)=>`<option value="${current-i}">${current-i}년</option>`).join('')}
async function refreshSession(){try{const data=await requestJson('/api/photo-kidsnote/session');state.connected=Boolean(data.connected);$('session-dot').classList.toggle('connected',state.connected);$('session-text').textContent=state.connected?'키즈노트 연결됨':'로그인이 필요합니다';$('btn-account-action').textContent=state.connected?'계정 변경':'로그인'}catch(error){toast(error.message)}}
function openLogin(){$('kidsnote-login-error').classList.add('hidden');$('kidsnote-login-modal').classList.remove('hidden');$('kidsnote-login-modal').setAttribute('aria-hidden','false');setTimeout(()=>$('kidsnote-username').focus(),80)}
function closeLogin(){$('kidsnote-login-modal').classList.add('hidden');$('kidsnote-login-modal').setAttribute('aria-hidden','true')}
async function login(event){event.preventDefault();const button=$('btn-kidsnote-login');button.disabled=true;button.querySelector('span').textContent='로그인 중…';try{await requestJson('/api/photo-kidsnote/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('kidsnote-username').value.trim(),password:$('kidsnote-password').value})});$('kidsnote-password').value='';closeLogin();await refreshSession();toast('키즈노트 계정이 연결되었습니다.')}catch(error){$('kidsnote-login-error').textContent=error.message;$('kidsnote-login-error').classList.remove('hidden')}finally{button.disabled=false;button.querySelector('span').textContent='로그인하고 연결하기'}}
async function loadPhotos(){if(!state.connected){openLogin();return}const button=$('btn-load-photos');button.disabled=true;$('lookup-progress').classList.remove('hidden');$('result-area').classList.add('hidden');$('start-guide').classList.add('hidden');$('download-bar').classList.add('hidden');try{const data=await requestJson(`/api/pc-photo-sources?year=${encodeURIComponent($('year-select').value)}`);state.photos=data.photos||[];$('date-select').innerHTML='<option value="">전체 날짜</option>'+(data.dates||[]).map(date=>`<option value="${date}">${shortDate(date)} · ${state.photos.filter(photo=>photo.takenAt.startsWith(date)).length}장</option>`).join('');state.date='';$('result-area').classList.remove('hidden');$('download-bar').classList.remove('hidden');render();toast(`최신 사진부터 ${state.photos.length}장을 조회했습니다.`)}catch(error){$('start-guide').classList.remove('hidden');toast(error.message)}finally{button.disabled=false;$('lookup-progress').classList.add('hidden')}}
function render(){state.date=$('date-select').value;const photos=state.date?state.photos.filter(photo=>photo.takenAt.startsWith(state.date)):state.photos;const hasPhotos=Boolean(photos.length);$('photo-count').textContent=`${photos.length}장`;$('selected-count').textContent=`${photos.length}장`;$('download-caption').textContent=state.date?displayDate(state.date):`${$('year-select').value}년 전체`;$('photo-list').replaceChildren(...photos.map(photoCard));$('photo-list').classList.toggle('hidden',!hasPhotos);$('empty-result').classList.toggle('hidden',hasPhotos);$('result-area').classList.toggle('empty-results',!hasPhotos);$('download-bar').classList.toggle('hidden',!hasPhotos);$('btn-download-date').disabled=!hasPhotos;$('btn-download-date').querySelector('span').textContent=state.date?'이 날짜 전체 받기':'연도 전체 받기';if(window.lucide)lucide.createIcons()}
function photoCard(photo){const card=document.createElement('article');card.className='photo-card';const image=document.createElement('img');image.loading='lazy';image.src=`/api/pc-photo-sources/${encodeURIComponent(photo.id)}/file`;image.alt='키즈노트 사진 미리보기';const meta=document.createElement('div');meta.className='photo-meta';const time=document.createElement('time');time.textContent=displayDate(photo.takenAt.slice(0,10));const link=document.createElement('a');link.href=`/api/pc-photo-sources/${encodeURIComponent(photo.id)}/file?download=1`;link.innerHTML='<span>한 장 받기</span><i data-lucide="download"></i>';meta.append(time,link);card.append(image,meta);return card}
function shortDate(value){const date=new Date(`${String(value).slice(0,10)}T00:00:00`);return Number.isNaN(date.getTime())?value:`${date.getMonth()+1}월 ${date.getDate()}일 (${['일','월','화','수','목','금','토'][date.getDay()]})`}
function displayDate(value){const date=new Date(`${String(value).slice(0,10)}T00:00:00`);return Number.isNaN(date.getTime())?value:`${date.getFullYear()}.${String(date.getMonth()+1).padStart(2,'0')}.${String(date.getDate()).padStart(2,'0')} (${['일','월','화','수','목','금','토'][date.getDay()]})`}
function downloadAll(){const query=state.date?`date=${encodeURIComponent(state.date)}`:`year=${encodeURIComponent($('year-select').value)}`;window.location.assign(`/api/pc-photo-download.zip?${query}`)}
document.addEventListener('DOMContentLoaded',()=>{localStorage.setItem('kidsnote-photo-view','mobile');initYears();refreshSession();if(window.lucide)lucide.createIcons();$('btn-kidsnote-session').addEventListener('click',openLogin);$('btn-account-action').addEventListener('click',openLogin);$('kidsnote-login-close').addEventListener('click',closeLogin);$('kidsnote-login-modal').addEventListener('click',event=>{if(event.target===$('kidsnote-login-modal'))closeLogin()});$('kidsnote-login-form').addEventListener('submit',login);$('btn-load-photos').addEventListener('click',loadPhotos);$('date-select').addEventListener('change',render);$('btn-download-date').addEventListener('click',downloadAll);$('btn-select-year-again').addEventListener('click',()=>{$('year-select').focus();window.scrollTo({top:0,behavior:'smooth'})});$('switch-pc').addEventListener('click',()=>localStorage.setItem('kidsnote-photo-view','pc'))});
