const $=s=>document.querySelector(s),API=location.port==='9000'?'/api/delivery':'/kidsnote-api';let adminPassword=sessionStorage.getItem('delivery-admin-password')||'',timer;
const fmtTime=v=>v?new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'-';const fmtSize=v=>v?`${(v/1024/1024).toFixed(1)} MB`:'-';const esc=v=>{const e=document.createElement('span');e.textContent=String(v??'');return e.innerHTML};const terminal=['completed','failed','cancelled'];const labels={queued:'대기','logging-in':'로그인 중',collecting:'목록 수집',downloading:'다운로드',compressing:'압축',emailing:'메일 발송',completed:'완료',failed:'실패',cancelled:'취소됨'};
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json','x-analytics-password':adminPassword,...options.headers},cache:'no-store'}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'요청을 처리하지 못했습니다.');return body}
function message(text,type=''){const e=$('#form-message');e.textContent=text;e.className=`message ${type}`}
async function load(){const [requests,jobs]=await Promise.all([api('/requests'),api('/jobs')]);renderRequests(requests);renderJobs(jobs);const active=jobs.filter(j=>!terminal.includes(j.status)).length;$('#active-count').textContent=active;$('#complete-count').textContent=jobs.filter(j=>j.status==='completed').length;$('#failed-count').textContent=jobs.filter(j=>j.status==='failed').length;$('#server-running').hidden=!active;clearTimeout(timer);if(active||requests.some(r=>r.status==='pending'))timer=setTimeout(load,2500)}
function renderRequests(items){const reusable=items.filter(r=>r.status==='pending'||(r.status==='accepted'&&r.canRerun));$('#requests').innerHTML=reusable.length?reusable.map(r=>{const pending=r.status==='pending';return `<article class="job request-item"><div class="job-top"><div><span class="badge ${pending?'':'completed'}">${pending?'신청 대기':'테스트 유지'}</span><strong>${esc(r.email)}</strong></div><time>${fmtTime(r.createdAt)}</time></div><div class="job-meta"><span>사진 기간 <b>${esc(r.year||'전체')}</b></span><span>폴더 <b>${r.folderMode==='day'?'년/월/일':'년/월'}</b></span><span>알림장 <b>${r.includeNotices?'포함':'미포함'}</b></span><span>접수번호 <b>${r.id.slice(0,8)}</b></span></div>${r.deliveryNote?`<div class="delivery-note"><span>전달 내용</span><p>${esc(r.deliveryNote)}</p></div>`:''}<div class="request-actions"><button class="${pending?'accept-request':'rerun-request'}" data-id="${r.id}">${pending?'수락하고 시작':'다시 시작'}</button>${pending?`<button class="reject-request cancel-job" data-id="${r.id}">거절</button>`:''}</div></article>`}).join(''):'<p class="empty">보관 중인 신청이 없습니다.</p>'}
function breakdownHtml(data){if(!data||!Object.keys(data).length)return '<p class="breakdown-empty">아직 연도별 집계가 없습니다.</p>';return Object.entries(data).sort((a,b)=>b[0].localeCompare(a[0])).map(([year,row])=>`<div class="breakdown-year"><strong>${esc(year)} <em>${row.total}장</em></strong><div>${Object.entries(row.months||{}).sort().map(([month,count])=>`<span>${month==='미상'?'월 미상':`${Number(month)}월`} <b>${count}</b></span>`).join('')}</div></div>`).join('')}
function renderJobs(jobs){$('#jobs').innerHTML=jobs.length?jobs.map(j=>{const done=j.progress?.downloaded||0,found=j.progress?.found||0,pct=found?Math.min(100,Math.round((done+(j.progress?.failed||0))/found*100)):0,active=!terminal.includes(j.status),breakdown=j.result?.breakdown||j.progress?.breakdown;return `<article class="job"><div class="job-top"><div><span class="badge ${j.status}">${labels[j.status]||j.status}</span><strong>${esc(j.email)}</strong></div><div class="job-tools">${active?`<button class="cancel-job cancel-running" data-id="${j.id}">취소</button>`:''}<time>${fmtTime(j.createdAt)}</time></div></div><div class="job-meta"><span>기간 ${!j.year?`<button class="breakdown-toggle" type="button">전체 ▾</button>`:`<b>${esc(j.year)}</b>`}</span><span>사진 <b>${j.result?.count??`${done}/${found||'-'}`}</b></span>${j.includeNotices?`<span>알림장 <b>${j.result?.noticeCount??'포함'}</b></span>`:''}<span>폴더 <b>${j.folderMode==='day'?'년/월/일':'년/월'}</b></span><span>ZIP <b>${fmtSize(j.result?.size)}</b></span></div>${!j.year?`<div class="breakdown" hidden>${breakdownHtml(breakdown)}</div>`:''}<div class="progress"><i style="width:${j.status==='completed'?100:pct}%"></i></div><p class="step ${j.status==='failed'?'error':''}">${esc(j.error||j.progress?.step||'')}</p></article>`}).join(''):'<p class="empty">진행 이력이 없습니다.</p>'}
async function login(value){adminPassword=value;await load();sessionStorage.setItem('delivery-admin-password',value);$('#login').hidden=true;$('#app').hidden=false}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{await login($('#admin-password').value);$('#login-error').textContent=''}catch(error){$('#login-error').textContent=error.message}});
$('#requests').addEventListener('click',async e=>{const accept=e.target.closest('.accept-request'),rerun=e.target.closest('.rerun-request'),reject=e.target.closest('.reject-request'),button=accept||rerun||reject;if(!button)return;button.disabled=true;try{const action=accept?'accept':rerun?'rerun':'reject';await api(`/requests/${button.dataset.id}/${action}`,{method:'POST'});message(reject?'신청을 거절하고 로그인 정보를 삭제했습니다.':rerun?'보관된 신청으로 작업을 다시 시작했습니다.':'신청을 수락해 작업을 시작했습니다.','success');await load()}catch(error){message(error.message,'error');button.disabled=false}});
$('#jobs').addEventListener('click',async e=>{const toggle=e.target.closest('.breakdown-toggle');if(toggle){const detail=toggle.closest('.job').querySelector('.breakdown');detail.hidden=!detail.hidden;toggle.textContent=detail.hidden?'전체 ▾':'전체 ▴';return}const button=e.target.closest('.cancel-running');if(!button)return;button.disabled=true;try{await api(`/jobs/${button.dataset.id}/cancel`,{method:'POST'});message('작업 취소를 요청했습니다.','success');await load()}catch(error){message(error.message,'error');button.disabled=false}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&adminPassword)load().catch(e=>message(e.message,'error'))});window.addEventListener('pageshow',()=>{if(adminPassword)load().catch(()=>{})});$('#refresh').addEventListener('click',()=>load().catch(e=>message(e.message,'error')));$('#logout').addEventListener('click',()=>{sessionStorage.removeItem('delivery-admin-password');location.reload()});if(adminPassword)login(adminPassword).catch(()=>sessionStorage.removeItem('delivery-admin-password'));
