location = /photo {
    proxy_pass http://127.0.0.1:3100;
    include proxy_params;
}

location ~ ^/(photo\.css|photo\.js)$ {
    proxy_pass http://127.0.0.1:3100;
    include proxy_params;
}

location ^~ /api/photos {
    proxy_pass http://127.0.0.1:3100;
    include proxy_params;
    proxy_read_timeout 3600s;
}

location ^~ /api/photo-kidsnote {
    proxy_pass http://127.0.0.1:3100;
    include proxy_params;
    proxy_read_timeout 120s;
}
